### ISSUE TITLE
matplotlib2tiz deprecated

### ISSUE THREAD

**Issue by pmwenzel** [T-TROUCHKINE/plotter#2]
Hi

the required pip package for matplotlib2tikz(https://pypi.org/project/matplotlib2tikz/) is not supported anymore. Therefore, the plotter library won't work anymore. Please update the dependencies to the new package named: https://pypi.org/project/tikzplotlib/

Thanks

**Comment by T-TROUCHKINE** [comment]
Hello !

I fixed the issue in [this commit](https://github.com/T-TROUCHKINE/plotter/commit/65ac14df83076076757b9d76563c607eedceeda4).

Thank you for your help.
